# Configuring Authentication for Git
# To clone a repository, Tekton needs a username and password of this repository. In this section, we will pass the Git username and password (using GitHub or GitLab) by creating a secret and mounting it to the service account.

apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/git-0: <YOUR-GIT-REPO-URL> # Add your Git repository URL
type: kubernetes.io/basic-auth
stringData:
  username: <Enter unencrypted username>
  password: <Enter unencrypted password>

  kubectl apply -f git-secret.yaml -n tekton-pipelines



# Pass this secret name in the service account’s secrets section. Edit the service account through the CLI and add the secret name in the secret section as shown below:

kubectl edit sa <service account name> -n tekton-pipelines



# Your service account looks as follows:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <Enter Service Account Name>
  namespace: tekton-pipelines
secrets:
  - name: basic-user-pass