# To illustrate how Pipelines and PipelineRuns work, let us consider an example to send a notification to a Slack channel after cloning a Git repository. We will start by creating a Pipeline using the following file:


apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-clone-notification
spec:
  params:
    - name: gitrevision-tag
  workspaces:
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo and be passed
                 to the next Task for the repo's README.md file to be read.
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value:
        - name: revision
          value: $(params.gitrevision-tag)
      workspaces:
        - name: output
          workspace: shared-data
    - name: send-notification
      runAfter: ["fetch-repo"]
      taskRef:
        name: send-to-channel-slack
      params:
        - name: token-secret
          value: token-secret
        - name: channel
          value: {CHANNEL ID}
        - name: message
          value: "Git cloned $(params.gitrevision-tag) branch "