# Multi-Tenant Scenarios and Service Account Overrides
# In environments hosting multiple tenants, distinct permissions or service accounts for different triggers are often necessary to ensure security and segregation of duties.

# The serviceAccountName field within the Trigger definition can override the default service account, enabling distinct permissions settings per trigger. It caters to differentiated access control in shared environments. Here's an example illustrating this concept:

triggers:
  - name: trigger-1
    serviceAccountName: trigger-1-sa # Override the service account to use for this trigger
    interceptors:
      - github:
          eventTypes: ["pull_request"]
    bindings:
      - ref: pipeline-binding # Reference to a TriggerBinding object
      - ref: message-binding # Reference to another TriggerBinding object
    template:
      ref: pipeline-template # Reference to a TriggerTemplate object

